export { calcTotalProductPrice } from './calc-total-product-price'
export { checkErrorType } from './check-error-type'
export { getOptionsFromSelectors } from './get-options-from-selectors'
export { getStringOfIngredients } from './get-string-of-ingredients'
export { validateOptions } from './validate-options'
export { handleApiCallInCart } from './handle-api-call-in-cart'
export { handleApiCall } from './handle-api-call'
export { getItemDescription } from './get-item-description'
export * from './is-prod'
export * from './VAT-calculation'
export * from './utils'
